#表明使用Druid连接池
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.2:3310/wwmust?setUnicode=true&characterEncoding=utf8
    username: root
    password: WANGwei2ming
  redis:
    database: 0
    host: 172.17.0.2
    jedis:
      pool:
        max-wait: -1
        max-active: 200
    port: 6379
    timeout: 1000

